### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 10: ordinal not in range(128)

### ISSUE THREAD

**Issue by kellymarchisio** [Kozea/Pyphen#22]
Pyphen is unable to handle ascii characters outside the first 128 (Related issue: #2). Even in English text, there are occasionally characters in the extended ascii or unicode sets that will appear such as below: 
Example:
```
p = Pyphen(lang='en_US')
p.inserted('She spent ¥130')
```
results in: `UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 10: ordinal not in range(128)`

Can you please provide error handling for these cases as opposed to the program breaking?

**Comment by liZe** [comment]
We have 2 different problems.

> results in: UnicodeDecodeError […] Can you please provide error handling for these cases as opposed to the program breaking?

I understand that it's not user-friendly, but I don't want to provide error handling. Here is why.

In Python, the type used to store characters is `unicode`. There's a problem: in Python 2, the syntax used to create unicode strings is `u'…'`, but people often use `'…'` instead. That's why in Python 3 they fixed this by using the `'…'` syntax to create unicode strings.

In Python 2, `'…'` strings are byte strings. Byte strings can be converted to character strings if you define an encoding. But without an encoding, bytes are not characters.

**Short answer: you should use `p.inserted(u'…')`.**

Calling `p.inserted('…')` is as wrong as calling `p.inserted(42)` or `p.inserted({'test': None})`. Just as I don't want check that parameters are integers or dicts, I don't want to check that they are bytestrings. :smile:

By the way: Python 3 is 10 years old. Python 2.7 official support will end in a little bit more than a year, and Pyphen may drop it even sooner. :wink:

> p.inserted(u'¥130 the crocodile')
> \# u'\xa5130 the crocodile'

`u'\xa5'` is the ["official" representation](https://docs.python.org/3.7/reference/datamodel.html#object.__repr__) of the `u'¥'` object in Python. Type `u'¥'` in a Python interpreter, you'll get u'\xa5'.
```python
>>> u'¥'
u'\xa5'
```

If you want a nice representation of unicode objects, you can use the `print` function:
```python
>>> print(p.inserted(u'¥130 the crocodile'))
¥130 the crocodile
```

**Comment by wmark** [comment]
```python
from pyphen import Pyphen
p = Pyphen(lang='en_US')

p.inserted(u'crocodile') in p.inserted(u'¥130 the crocodile')
```

expected: `true`
got: `false`

**Comment by liZe** [comment]
@wmark Pyphen hyphenates words, not sentences. I'll update the website about that.
