### ISSUE TITLE
Why the English word 'Howdy' is not hyphenated?

### ISSUE THREAD

**Issue by santho3110** [Kozea/Pyphen#27]
It would be helpful if some one explains how this works.

hyphenated_word = hyphen_dict.inserted("howdy")
print(hyphenated_word)

>> howdy

**Comment by liZe** [comment]
Hello!

> It would be helpful if some one explains how this works.

I’m not sure to understand your question.

If you want to understand how hyphenation works in English, I’m not sure that I can help you. The [Syllabification](https://en.wikipedia.org/wiki/Syllabification] article on Wikipedia gives interesting pointers to understand how it works (spoiler: you have to use a dictionary).

If you’re expecting this word to be hyphenated, then the problem is in the dictionary, not in Pyphen. An [online hunspell-based tool](http://www.ushuaia.pl/hyphen/?ln=en) also gives no hyphenation. You can try to report a bug in [LibreOffice/dictionaries](https://github.com/LibreOffice/dictionaries), that’s where Pyphen dictionaries come from.
