### ISSUE TITLE
Hungarian hyphenation is faulty in case of vowel-consonant-vowel-* words

### ISSUE THREAD

**Issue by aswna** [Kozea/Pyphen#61]
Hello,
using latest pyphen (0.14.0), there seems to be an issue with the hyphenation of Hungarian words starting as vowel-consonant-vowel-*. E.g.: "alak" should be hyphenated as "a-lak" (currently not hyphenated by pyphen), or "alaktalan" as "a-lak-ta-lan" (incorrectly hyphenated as "alak-ta-lan" by pyphen).

I saw you suggested here to check with https://www.ushuaia.pl/hyphen/?ln=en (selecting language: Hungarian). The hyphenation of these type of words are also faulty there. Also checked these words in LibreOffice (7.3.7.2), it has the same issue.

Notes:
- have not checked previous releases, just started to try pyphen
- could not find any other type of words incorrectly hyphenated, e.g. "láda", "labda", "drága" are all hyphenated correctly ("lá-da", "lab-da", "drá-ga") by these tools.

What should be used for cross-checking instead of the above is https://helyesiras.mta.hu/helyesiras/default/hyph# .
Note: MTA (mta.hu) is the National Academy of Science in Hungary.
The hyphenations I checked here were all correct, including the above words, too.

Thanks for looking into this!

**Comment by liZe** [comment]
Hi!

Thanks for this report.

> I saw you suggested here to check with https://www.ushuaia.pl/hyphen/?ln=en (selecting language: Hungarian). The hyphenation of these type of words are also faulty there. Also checked these words in LibreOffice (7.3.7.2), it has the same issue.

Then it means that the problem (or maybe it’s a known limitation) comes from the dictionary. The best way to solve this is to talk with the authors of the dictionary, you’ll find more information about them in [this file](https://github.com/Kozea/Pyphen/blob/main/pyphen/dictionaries/README_hyph_hu_HU.txt).

> What should be used for cross-checking instead of the above is https://helyesiras.mta.hu/helyesiras/default/hyph# .

I propose to use ushuaia.pl because it uses the same dictionary as Pyphen but not the same code. So, if users have the same problem with Pyphen and ushuaia.pl, it means that the problem is in the dictionary (that we don’t maintain, and that we can’t fix), and not in the code (that we maintain and can fix.)
